shortly/lib/shortly_web/router.ex
defmodule ShortlyWeb.Router do
  use ShortlyWeb, :router
  use Pow.Phoenix.Router

  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShortlyWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through [:browser, :get_remote_ip]

    live "/", ShortlyWeb.PageLive, :index, layout: "homepage.html"
    get "/:slug", ShortlyWeb.PageController, :page_redirect

    pow_session_routes()
  end

  scope "/registration", Pow.Phoenix, as: "pow" do
    pipe_through [:browser, :protected]

    resources "/", RegistrationController, singleton: true, only: [:edit, :update, :delete]
  end

  scope "/admin", ShortlyWeb.Admin, as: :admin do
    pipe_through [:browser, :protected]

    resources "/domains", DomainController
    resources "/urls", UrlController
    resources "/visits", VisitController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShortlyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  import Phoenix.LiveDashboard.Router

  scope "/admin" do
    pipe_through [:browser, :protected]

    live_dashboard "/dashboard",
      metrics: ShortlyWeb.Telemetry,
      metrics_history: {ShortlyWeb.TelemetryStorage, :metrics_history, []},
      ecto_repos: [Shortly.Repo]
  end

  defp get_remote_ip(conn, _) do
    put_session(conn, :remote_ip, conn.remote_ip)
  end
end

shortly/lib/shortly_web/views/layout_view.ex
defmodule ShortlyWeb.LayoutView do
  use ShortlyWeb, :view
end

shortly/lib/shortly_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Shortly", suffix: " · Phoenix Framework" %>
    <link
      rel="stylesheet"
      href="<%= Routes.static_path(@conn, "/css/app.css") %>"
    />
    <script
      defer
      type="text/javascript"
      src="<%= Routes.static_path(@conn, "/js/app.js") %>"
    ></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if Pow.Plug.current_user(@conn) do %>
              <li>
                <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %>
              </li>
              <span
                ><a
                  href="<%= Routes.pow_registration_path(@conn, :edit) %>"
                ><%= @current_user.email %></a
              ></span>
              <span><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></span>
            <% end %>
          </ul>
        </nav>
        <a href="/" class="phx-logo">
          <img
            src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>"
            alt="Phoenix Framework Logo"
          />
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

shortly/lib/shortly_web/templates/layout/torch.html.eex
<html>
  <head>
    <title>Admin</title>
    <link
      rel="stylesheet"
      href="<%= Routes.static_path(@conn, "/torch/theme.css") %>"
    />
  </head>

  <body class="<%= Torch.PageView.body_classes(@conn) %>">
    <header>
      <section id="torch-account-info">
        <div class="torch-container">
          <span
            ><a
              href="<%= Routes.pow_registration_path(@conn, :edit) %>"
            ><%= @current_user.email %></a
          ></span>
          <span><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></span>
        </div>
      </section>

      <section id="torch-nav">
        <div class="torch-container">
          <div class="torch-logo">
            <a href="/">
              <h3>Torch</h3>
            </a>
          </div>
          <nav class="torch-nav">
            <a href="<%= Routes.admin_url_path(@conn, :index) %>">Urls</a>
            <a href="<%= Routes.admin_visit_path(@conn, :index) %>">Visits</a>
            <a href="<%= Routes.admin_domain_path(@conn, :index) %>">Domains</a>
          </nav>
        </div>
      </section>
    </header>

    <%= Torch.FlashView.render("_flash_messages.html", assigns) %>
    <%= @inner_content %>
    <script src="<%= Routes.static_path(@conn, "/torch/torch.js") %>"></script>
  </body>
</html>